restunts: asm c
	make -C dos

restunts-original: asmorig
	make -C dos/asmorig /DTARGET=original; fi

asm:
	make -C asm

asmorig:
	make -C asmorig

#restunts-sdl:
#	cd sdl
#	if [ -f makefile ] ; then make; fi
#	cd ..
#
#repldump: asm c
#	cd repldump
#	if [ -f makefile ] ; then make; fi
#	cd ..
#
#repldump-original: asmorig
#	cd repldump
#	if [ -f makefile ] ; then make /DTARGET=original; fi
#	cd ..

#clean:
#	cd dos
#	if [ -f makefile ] ; then make clean; fi
#	cd ..
#	cd c
#	if [ -f makefile ] ; then make clean; fi
#	cd ..
#	cd asm
#	if [ -f makefile ] ; then make clean; fi
#	cd ..
#	cd asmorig
#	if [ -f makefile ] ; then make clean; fi
#	cd ..
#	cd sdl
#	if [ -f makefile ] ; then make clean; fi
#	cd ..
#	cd repldump
#	if [ -f makefile ] ; then make clean; fi
#	cd ..
